platform :ios, '8.0'

target 'ECO' do
    
    pod 'SDCycleScrollView'
    pod 'MBProgressHUD'
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'XHLogHelper'
    pod 'FMDB'
    pod 'IQKeyboardManager'
end


